### ISSUE TITLE
Weird issue with Libmemcached Metadata and background mode

### ISSUE THREAD

**Issue by Jurigag** [SidRoberts/phalcon-cron#14]
When using manager in background mode with phalcon Libmemcached metadata(no matter if persistent connection or not) with php-memcached 3.1.5 and libmemcached 1.0.18 i have really weird issue that sometimes there are errors returned like `'Column 'created' doesn't belong to any of the selected models (1),`. This happens only on libmemcached, using memcache for some reason works.

Also when using foreground mode it works fine too. It seems that `pcntl_fork` is causing some problems, also it sometimes happens, sometimes not. Totally random. Sometimes there are wrong values returned for certain keys etc. Not sure what exactly it's happening and what to even investigate.

I don't know, maybe someone got this issue too and know the answer what's the problem, really struggle with this.

**Comment by Urvin** [comment]
What database do you use?
If Postgres, do you use PGBouncer?

**Comment by Urvin** [comment]
Anyway, try to add
`'options' => [
        \PDO::ATTR_EMULATE_PREPARES => true,
]`
In your DB config

**Comment by Jurigag** [comment]
Using Mysql at this moment. Also as i stated above - this happens only in background mode, when running foreground - issue never happens.

**Comment by Jurigag** [comment]
I managed to solve this finally - i added const that i run it in background and then set `$options['persistent_id'] = 'fork-' . getmypid();` like this and it works without issues now.
