### ISSUE TITLE
Service 'console' wasn't found in the dependency injection container

### ISSUE THREAD

**Issue by Zaszczyk** [SidRoberts/phalcon-cron#5]
I get such error:
Service 'console' wasn't found in the dependency injection container
when I call:
/usr/bin/php /vagrant/www/cli.php cron
I think it is caused by:

```
public function runInForeground()
    {
        ob_start();

        $this->getDI()->get("console")->handle(
            $this->getBody()
        );

        $contents = ob_get_contents();

        ob_end_clean();

        return $contents;
    }
```

in vendor/sidroberts/phalcon-cron/src/Job/Phalcon.php
What should be instanced as 'console' in DI?

**Comment by SidRoberts** [comment]
You'll need to add your console instance to the DI (in `cli.php`). See https://docs.phalconphp.com/en/latest/reference/cli.html#running-tasks-in-a-chain

``` php
$console = new \Phalcon\Cli\Console();

// ...

$di->setShared("console", $console);

// ...

$console->handle($arguments);
```

I'll update the README tonight to make it clearer. :)
