### ISSUE TITLE
Right implementation?

### ISSUE THREAD

**Issue by rafaelbecks** [SidRoberts/phalcon-cron#9]
I've been reading the docs but I can't figure out how to get the library running.

I got a phalcon clit task running Ok, the idea is create a cron job to execute that task.

This is my code

```
 $this->app->di->set(
            "cron_data_fetch",
            function () {
                $cron = new \Sid\Phalcon\Cron\Manager();
                 $cron->add(
                    new \Sid\Phalcon\Cron\Job\System(
                        "* 8 * * *",
                        "php console.php mytask action"
                    )
                );
            });

```

What else I need to do? I also attatch the console to the DI with

```
$console = new \Phalcon\Cli\Console();
$di->setShared("console", $console);
```

And I tried adding the cron this way

```
$cron->add(
            new \Sid\Phalcon\Cron\Job\Phalcon(
                "* 8 * * *",
                [
                    "task"   => "task",
                    "action" => "action",
                    "params" => "params"
                ]
            )
        );
```

But it's not working

Thanks

**Comment by SidRoberts** [comment]
Do you have a Cron CLI Task class?:

``` php
<?php

class CronTask extends \Phalcon\Cli\Task
{
    public function mainAction()
    {
        $this->cron_data_fetch->runInBackground();
    }
}
```

You'll also need to add this task to `/etc/crontab`:

```
* * * * * /usr/bin/php /path/to/cli.php cron
```

**Comment by rafaelbecks** [comment]
I have the task but without calling the runInBackground method. I thought that adding the cron to the DI would add the task to the crontab under the hood. What is the benefit of use the library methods over only add directly the cli task to the crontab?

Thanks for your answer

**Comment by SidRoberts** [comment]
Ahh, I see. The whole point of adding it to the DI is so that you can interact with it anywhere in your application. It's not necessary. Alternatively, you could just write it in the task:

``` php
<?php

class CronTask extends \Phalcon\Cli\Task
{
    public function mainAction()
    {
        $cron = new \Sid\Phalcon\Cron\Manager();

        $cron->add(
            new \Sid\Phalcon\Cron\Job\System(
                "* 8 * * *",
                "php console.php mytask action"
            )
        );

        $cron->runInBackground();
    }
}
```

The whole point of this library is to make it easier to control and maintain the crontab. Instead of changing the crontab directly, you can just write it in PHP and this will help ensure that you're development and production environments are identical.

You could also save your cron jobs in a database and be able to easily add them to the cron manager in PHP.

**Comment by rafaelbecks** [comment]
Ok, now I get it. Yes, that's why I was trying to use the library, I didn't want to interact with the crontab itself and wanted to make the code more maintainable.

I will close the issue, thank you so much for the help
